Project113_G3/Models/Datagame.cs
namespace Project113_G3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Datagame")]
    public partial class Datagame
    {
        public int Id { get; set; }

        [StringLength(50)]
        public string NameGame { get; set; }

        [StringLength(50)]
        public string TypeGame { get; set; }

        [StringLength(250)]
        public string Description_Game { get; set; }

        [StringLength(50)]
        public string url { get; set; }
    }
}

Project113_G3/Controllers/DatagamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Project113_G3.Models;

namespace Project113_G3.Controllers
{
    public class DatagamesController : Controller
    {
        private Datagame1 db = new Datagame1();

        // GET: Datagames
        public ActionResult Index()
        {
            return View(db.Datagame.ToList());
        }

        // GET: Datagames/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Datagame datagame = db.Datagame.Find(id);
            if (datagame == null)
            {
                return HttpNotFound();
            }
            return View(datagame);
        }

        // GET: Datagames/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Datagames/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NameGame,TypeGame,Description_Game,url")] Datagame datagame)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    file.SaveAs(path);
                    datagame.url = fileName;

                }
                db.Datagame.Add(datagame);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(datagame);
        }

            // GET: Datagames/Edit/5
            public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Datagame datagame = db.Datagame.Find(id);
            if (datagame == null)
            {
                return HttpNotFound();
            }
            return View(datagame);
        }

        // POST: Datagames/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NameGame,TypeGame,Description_Game,url")] Datagame datagame)
        {
            if (ModelState.IsValid)

            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    file.SaveAs(path);
                    datagame.url = fileName;

                }
                db.Entry(datagame).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(datagame);
        }

        // GET: Datagames/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Datagame datagame = db.Datagame.Find(id);
            if (datagame == null)
            {
                return HttpNotFound();
            }
            return View(datagame);
        }

        // POST: Datagames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Datagame datagame = db.Datagame.Find(id);
            db.Datagame.Remove(datagame);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project113_G3/Views/Datagames/Create.cshtml
@model Project113_G3.Models.Datagame

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>




@using (Html.BeginForm("Create", "Datagames", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Datagame</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NameGame, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameGame, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameGame, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeGame, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeGame, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeGame, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description_Game, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description_Game, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description_Game, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control", type = "file" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project113_G3/Views/Datagames/Delete.cshtml
@model Project113_G3.Models.Datagame

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Datagame</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameGame)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameGame)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeGame)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeGame)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description_Game)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description_Game)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project113_G3/Views/Datagames/Details.cshtml
@model Project113_G3.Models.Datagame

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Datagame</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameGame)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameGame)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeGame)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeGame)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description_Game)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description_Game)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            <img src=@Url.Content("~/Content/images/"+(Model.url)) style="width: 100px;height: auto" />
        </dd>

        

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project113_G3/Views/Datagames/Edit.cshtml
@model Project113_G3.Models.Datagame

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Datagame</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.NameGame, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameGame, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameGame, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeGame, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeGame, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeGame, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description_Game, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description_Game, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description_Game, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project113_G3/Views/Datagames/Index.cshtml
@model IEnumerable<Project113_G3.Models.Datagame>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NameGame)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeGame)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description_Game)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.url)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NameGame)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeGame)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description_Game)
            </td>
  
            <td>
                <img src=@Url.Content("~/Content/images/"+(item.url)) style="width: 100px;height: auto" />
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>



        </tr>
    }

</table>